### ISSUE TITLE
Move DatasetInfo from `datasets_infos.json` to the YAML tags in `README.md`

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets#4876]
Currently there are two places to find metadata for datasets:
- datasets_infos.json, which contains **per dataset config**
  - description
  - citation
  - license
  - splits and sizes
  - checksums of the data files
  - feature types
  - and more
- YAML tags, which contain
  - license
  - language
  - train-eval-index
  - and more

It would be nice to have a single place instead. We can rely on the YAML tags more than the JSON file for consistency with models. And it would all be indexed by our back-end directly, which is nice to have. 

One way would be to move everything to the YAML tags except the checksums (there can be tens of thousands of them). The description/citation is already in the dataset card so we probably don't need to have them in the YAML card, it would be redundant.

Here is an example for SQuAD
```yaml

download_size: 35142551
dataset_size: 89789763
version: 1.0.0
splits:
- name: train
  num_examples: 87599
  num_bytes: 79317110
- name: validation
  num_examples: 10570
  num_bytes: 10472653
features:
- name: id
  dtype: string
- name: title
  dtype: string
- name: context
  dtype: string
- name: question
  dtype: string
- name: answers
  struct:
  - name: text
    list:
      dtype: string
  - name: answer_start
    list:
      dtype: int32
```

Since there is only one configuration for SQuAD, this structure is ok. For datasets with several configs we can see in a second step, but IMO it would be ok to have these fields per config using another syntax
```yaml
configs:
- config: unlabeled
  splits:
  - name: train
    num_examples: 10000
  features:
  - name: text
    dtype: string
- config: labeled
  splits:
  - name: train
    num_examples: 100
  features:
  - name: text
    dtype: string
  - name: label
    dtype: ClassLabel
    names:
    - negative
    - positive
```
So in the end you could specify a YAML tag either at the top level (for all configs) or per config in the `configs` field

Alternatively we could keep config specific stuff in the `dataset_infos.json` as it it today

Not sure yet what's the best approach here but cc @julien-c @mariosasko @albertvillanova @polinaeterna for feedback :)

**Comment by julien-c** [comment]
also @osanseviero @Pierrci @SBrandeis potentially

**Comment by SBrandeis** [comment]
Love this in principle 🚀 

Let's keep in mind users might rely on `dataset_infos.json` already.

I'm not convinced by the two-syntax solution, wouldn't it be simpler to have only one syntax with a `default` config for datasets with only one config? ie, always having the `configs` field. This makes parsing the metadata easier IMO.

Might also be good to wrap the tags under a `datasets_info` tag as follows:

```yaml
description: ...
citation: ...
dataset_infos:
  download_size: 35142551
  dataset_size: 89789763
  version: 1.0.0
  configs:
    - ...
[...]
```

Let's also keep in mind that extracting YAML metadata from a markdown readme is a bit more fastidious for users than just parsing a JSON file.

**Comment by lhoestq** [comment]
> Let's keep in mind users might rely on dataset_infos.json already.

Yea we'll full full backward compatibility

> Let's also keep in mind that extracting YAML metadata from a markdown readme is a bit more fastidious for users than just parsing a JSON file.

The main things that may use or ingest these data IMO are:
- users in the UI or IDE
- `datasets` to populate `DatasetInfo` python object
- moon landing which is already parsing YAML

Am I missing something ? If not I think it's ok to use YAML

> Might also be good to wrap the tags under a datasets_info tag as follows:

Maybe one single syntax like this then ?
```yaml
dataset_infos:
- config: unlabeled
  download_size: 35142551
  dataset_size: 89789763
  version: 1.0.0
  splits:
  - name: train
    num_examples: 10000
  features:
  - name: text
    dtype: string
- config: labeled
  download_size: 35142551
  dataset_size: 89789763
  version: 1.0.0
  splits:
  - name: train
    num_examples: 100
  features:
  - name: text
    dtype: string
  - name: label
    dtype: ClassLabel
    names:
    - negative
    - positive
```
and when you have only one config
```yaml
dataset_infos:
- config: default
  splits:
  - name: train
    num_examples: 10000
  features:
  - name: text
    dtype: string
```
