### ISSUE TITLE
Support for identifier-based automated split construction

### ISSUE THREAD

**Issue by alex-hh** [huggingface/datasets#7287]
### Feature request

As far as I understand, automated construction of splits is currently based on either file names or directory structure.

It would be pretty useful to allow splits to be based on identifiers of individual examples

### Motivation

The main motivation would be that all data files could be stored in a single directory, and multiple sets of splits could be generated from the same data. This is often useful for large datasets with multiple distinct sets of splits.

This could all be configured via the README.md yaml configs

### Your contribution

May be able to contribute.

**Comment by lhoestq** [comment]
Hi ! You can already configure the README.md to have multiple sets of splits, e.g.

```yaml
configs:
- config_name: my_first_set_of_split
  data_files:
  - split: train
    path: *.csv
- config_name: my_second_set_of_split
  data_files:
  - split: train
    path: train-*.csv
  - split: test
    path: test-*.csv
```
