### ISSUE TITLE
`ArrowNotImplementedError: Unsupported cast from list<item:struct<…>> to struct` when loading nested `Sequence(Features)` JSONL

### ISSUE THREAD

**Issue by AHS-uni** [huggingface/datasets#7590]
### Describe the bug

When loading a JSONL dataset with a top‐level `tags` field defined as a list of structs (via `Sequence(Features({...}))`), Hugging Face Datasets still infers `tags` as a single `struct<…>`, and then PyArrow throws:

```
ArrowNotImplementedError: Unsupported cast from list<item: struct<…>> to struct using function cast_struct
```

even when the full nested `Features` schema is passed to `load_dataset(..., features=…)` and `streaming=False`. This prevents loading any entries where `tags` has more than one element (or is empty).

### Steps to reproduce the bug

[Colab Link](https://colab.research.google.com/drive/1FZPQy6TP3jVd4B3mYKyfQaWNuOAvljUq#scrollTo=qkigsmEZLrnY)

### Expected behavior

The `tags` field should be recognized as `list<struct<name,target,comment>>`, and both empty lists (`[]`) and multi-element lists should load without casting errors.

### Environment info

* **datasets** version: `3.6.0`
* **pyarrow** version: `20.0.0`
* **Python**: 3.12.10
* **OS**: Ubuntu 24.04.02 LTS

**Comment by AHS-uni** [comment]
Hello @Flink-ddd 

I updated the minimal example and included both JSON and JSONL minimal examples in the Colab notebook. 

Here is the minimal  JSON file convenience (can't upload JSONL files).

[mini.json](https://github.com/user-attachments/files/20535145/mini.json)

I've also found a number of similar issues which describe a similar problem:

[7569](https://github.com/huggingface/datasets/issues/7569) (Open)
[7137](https://github.com/huggingface/datasets/issues/7137) (Open)
[7501](https://github.com/huggingface/datasets/issues/7501) (Closed)
[2434](https://github.com/huggingface/datasets/issues/2434) (Closed)

The closed issues don't really address the problem (IMO). [7501](https://github.com/huggingface/datasets/issues/2434) provides a workaround (using a Python list instead of `Sequence`), but it seem precarious.

**Comment by lhoestq** [comment]
Hi ! `Sequence({...})` corresponds to a struct of lists ([docs](https://huggingface.co/docs/datasets/v3.6.0/en/package_reference/main_classes#datasets.Features)). This come from Tensorflow Datasets.

If you want to use a list of structs, you should use `[{...}]`, e.g.

```python
item = {
    "id":   Value("string"),
    "data": Value("string"),
}

features = Features({
    "list": [item],
})
```

**Comment by ain-soph** [comment]
@lhoestq Thanks for your explanation, which helps me understand the logic behind. But I'm confused how to define that in `README.md`?

My jsonl data is: 
```
{"answers": [{"text": "text1", "label": "label1"}, {"text": "text2", "label": "label2"},]}
{"answers": [{"text": "text1", "label": "label1"}, {"text": "text2", "label": "label2"},]}
...
```

My README.md look like
```
dataset_info:
- config_name: default
  features:
  - name: answers
    sequence:
    - name: text
      dtype: string
    - name: label
      dtype: string
```
I understand `sequence` here is not correct, but what's the correct format? I tried following (`sequence -> dtype`)and seems not the case:
```
dataset_info:
- config_name: default
  features:
  - name: answers
    dtype:
    - name: text
      sequence: string
    - name: label
      sequence: string
```

**Comment by lhoestq** [comment]
The `List` type which doesn't have the weird dict behavior of `Sequence` has been added for `datasets` 4.0 (to be released next week). Feel free to install `datasets` from source to try it out :)
EDIT: it's out !

You can fix the issue using `List` instead of `Sequence`, e.g. in the case of the original post:

```python
# Feature spec with List of structs
item = {
    "id":   Value("string"),
    "data": Value("string"),
}

features = Features({
    "list": List(item),
})
```

for which the README.md is

```yaml
dataset_info:
- config_name: default
  features:
  - name: list
    list:
    - name: id
      dtype: string
    - name: data
      dtype: string
```
